### ISSUE TITLE
Make it work offline

### ISSUE THREAD

**Issue by ritz078** [transform-it/transform-www#23]
Ideas or PR welcome.

**Comment by akosyakov** [comment]
If you mean like an extension to VS code, Atom, Eclipe or other tools. You can leverage the language server protocol. It is supported already by following tools: https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations#editors-ides-supporting-the-protocol.

You will need to use [this library](https://github.com/Microsoft/vscode-languageserver-node/tree/master/server) to create the transform-www server that provides transformation commands for json files.

**Comment by akosyakov** [comment]
I guess it will depend on https://github.com/ritz078/transform-www/issues/9.

**Comment by morajabi** [comment]
I think @ritz078 means something like Service Workers (?)

**Comment by akosyakov** [comment]
@morajabi perhaps, but ability to create interfaces from JSON directly in the tool instead of switching to the browser could be cool

**Comment by ritz078** [comment]
These two are totally different. Here I meant using service workers to make the website work offline in the browser and what @morajabi means is a separate concern that needs multiple steps.

**Comment by ritz078** [comment]
@akosyakov We are planning to make separate packages so you won't need to have any server. you can directly use the module and make a plugin.

**Comment by akosyakov** [comment]
@ritz078 ok, got you. A language server is not a real "server" in sense of web. It is an interface which tools understand to add support for new languages, so it can be developed once as a plugin and deployed to all tools listed.

**Comment by ritz078** [comment]
Got it. Thanks.

**Comment by morajabi** [comment]
@ritz078 
> and what @morajabi means is a separate concern that needs multiple steps.
I said Service Workers too:
> I think @ritz078 means something like Service Workers (?)

**Comment by ritz078** [comment]
@morajabi That was an error in mentioning. I corrected it.
