### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by ritz078** [transform-it/transform-www#24]
I will be busy with some other projects in coming days. This project seems to be stable in its current state but I will like to see it evolve and I will need some helping hand. Let me know if you are interested.

cc @morajabi

**Comment by morajabi** [comment]
As long as I'm able to do something I'd be happy! But I can't promise to ALWAYS be available.

**Comment by ritz078** [comment]
As I said I think this project seems to be stable to I guess it won't take a lot of time.

**Comment by morajabi** [comment]
So, let's do this. 👍

**Comment by ritz078** [comment]
Sent you an invite. Also I am not leaving this project just need a bit of help with too many projects.

**Comment by morajabi** [comment]
@ritz078 It can't be done without you.
