### ISSUE TITLE
Migrate to the Monaco editor

### ISSUE THREAD

**Issue by akosyakov** [transform-it/transform-www#27]
See https://github.com/ritz078/transform-www/pull/20#issuecomment-326750270

**Comment by ritz078** [comment]
The only pro I can think about is editing experience but I also think that most of the time users will copy and paste the JSON or fetch it from an URL.

**Comment by akosyakov** [comment]
If you go for https://github.com/ritz078/transform-www/issues/23#issuecomment-326751773 then the Monaco editor could be easily integrated with language servers via https://github.com/TypeFox/monaco-languageclient, I am not aware that Ace or CodeMirror can do it

**Comment by ritz078** [comment]
Yes but its not needed on the website because its already simple. Everything is happening on the client side so I don't think we will ever need a server. separate packages will be enough.

**Comment by ritz078** [comment]
Don't think this is needed anymore.
