### ISSUE TITLE
Move to a separate org

### ISSUE THREAD

**Issue by ritz078** [transform-it/transform-www#28]
Continuing from #9 

@morajabi Lets keep the discussion here.

Any name in mind ? **transform** is not available

**Comment by morajabi** [comment]
Do we want to rename the main package too?

**Comment by ritz078** [comment]
Yes. But we can use scoped npm name for that like @Orgname/transform like storybook does . So that won't be an issue.

**Comment by AsaAyers** [comment]
Are you considering using [scoped npm packages](https://docs.npmjs.com/misc/scope)? If you do, then you can name the packages anything you want without running into name conflicts with anyone else.

**Comment by ritz078** [comment]
@AsaAyers Yes thats what I have in mind.

**Comment by morajabi** [comment]
Just a suggestion: **any-to-any** or **transform-it**

**Comment by ritz078** [comment]
I like transform-it

**Comment by morajabi** [comment]
After your confirmation, we can sketch a logo for it.

**Comment by ritz078** [comment]
That's the last thing to do. First we need to create the tools as that's the most important thing.

**Comment by morajabi** [comment]
I love designing. Nevermind! 

What? Tell me it's yours, please!! https://github.com/transform-it

**Comment by ritz078** [comment]
So do I 😄 Yes its mine.

**Comment by ritz078** [comment]
Also I have asked the owner of **transform** if he will be willing to give up the username. so I will wait a few days.

**Comment by morajabi** [comment]
@ritz078 I don't think **Transform** is even able to see your message! Anyway it's worth trying.

**Comment by ritz078** [comment]
Yes. If he doesn't reply, will move to transform-it

**Comment by morajabi** [comment]
@ritz078 Great! I'll make another issue for the logo just to be there for later.

**Comment by ritz078** [comment]
closing this as we have moved to an org.
