### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by morajabi** [transform-it/transform-www#29]
After finalizing the move to our new org, we'll design logo here.

**Comment by ritz078** [comment]
I have used a placeholder logo for now.

**Comment by morajabi** [comment]
Is it our logo? It's good I suppose, tell me what parts don't you like, how it can be redesigned to match what you want.

**Comment by ritz078** [comment]
yes it's our logo. It has been on the website since long. I don't have any problem with it.

**Comment by morajabi** [comment]
I think we should keep it for now! it's good!
