### ISSUE TITLE
Make it mobile friendly

### ISSUE THREAD

**Issue by ritz078** [transform-it/transform-www#33]

**Comment by gyandeeps** [comment]
I was planning to work on this but codemirror is a pain to work with (and its inside a dependency). Even currently you can't scroll on the left editor.

**Comment by ritz078** [comment]
I think it doesn't make sense to make it mobile friendly. So I will close this for now. But the scrolling part definitely needs to be fixed.

**Comment by brunolemos** [comment]
Came here to ask for mobile friendly.
It makes sense not necessarily in the way "it will be used extensively on mobile" but, for example, someone shared this on twitter and I can't check right now if this works, can't test it, check if it solves my issue, etc. 

![12b64600-3cba-48cc-99d8-79275057733b](https://user-images.githubusercontent.com/619186/36873013-fe2ed548-1d85-11e8-8c4f-1917399d8346.png)

**Comment by morajabi** [comment]
@ritz078 Maybe some kinda demo page with fixed data would work?

**Comment by ritz078** [comment]
I guess that makes sense since this is anyways not going to be useful on mobile. So I can actually replace this code part with features and an image.
