### ISSUE TITLE
[Suggestion] Add ES6 option for HTML to JSX - Create Class option

### ISSUE THREAD

**Issue by shug0** [transform-it/transform-www#36]
It will be nice to have another checkbox for ES6 format for the create class of HTML to JSX in the React Section.

Maybe it's too much for the tools. 

Thanks for this awesome tools 👍

**Comment by ritz078** [comment]
I am thinking of totally removing it. There is no point giving anyone the JS part. Most of the time users only need the JSX part. I am currently creating a module that will convert svg to `react-native-svg` compatible svg. So I was thinking of replacing that button with this.

I am not yet sure about removing it. But I don't see a lot of usage for that.

**Comment by shug0** [comment]
Yeah I agree with this, the simple transform purpose is a bit too much if you want to include all "compatible" ways to write a class. I close this thanks for consideration 😼
