### ISSUE TITLE
JSON to scala case class will produce weird case classes

### ISSUE THREAD

**Issue by copumpkin** [transform-it/transform-www#45]
In the example at https://transform.now.sh/json-to-scala-case-class, it translates a JSON array to a Scala `Array`. Unfortunately, Scala `Array` is just a wrapper for Java arrays, which have reference equality. That means that equality between case class instances produced using this tool will not have sensible equality (because distinct arrays containing the same elements will be considered different).

A simple solution would be to switch `Array` to `Seq` or `IndexedSeq`, which will have sensible equality.

**Comment by ritz078** [comment]
So if I am understanding you correctly, even `List` is a valid alternative right ? I am not a Scala user to confirming before making any changes.

**Comment by copumpkin** [comment]
Yeah, `List` would be fine, although it's a singly linked list. `Seq` and `IndexedSeq` are interfaces and will often have more efficient datastructures behind the scenes, but for data modeling they're all just sequences so it shouldn't matter.

Another consequence I forgot to mention in the bug report is that `Array` also has an awful `toString` instance, so any case classes using arrays will just print a horrible hex object ID rather than the contents of the array 😄 

Thanks!

**Comment by ritz078** [comment]
Fine then I am going ahead with `Seq` and making the changes. Thank you.

**Comment by ritz078** [comment]
fix is live.

**Comment by copumpkin** [comment]
Thank you for the quick response!
