### ISSUE TITLE
JSON to Serde doesn't handle keywords or spaces

### ISSUE THREAD

**Issue by Roughsketch** [transform-it/transform-www#46]
I guess this is two issues in one, but these are things I've noticed while trying to use it.

1. It doesn't handle renaming keywords. I've seen this issue with APIs that will return something like

```json
{
    "type": 1
}
```

Output will give you the following struct:
```rust
#[derive(Serialize, Deserialize)]
struct RootInterface {
  type: i64,
}
```

But it should be giving something like this:
```rust
#[derive(Serialize, Deserialize)]
struct RootInterface {
  #[serde(rename = "type")]
  kind: i64,
}
```

2. Key with spaces will produce invalid Rust. For instance, the following JSON will produce the following struct with an invalid identifier:

```json
{
  "cat dog": 1
}
```
```rust
#[derive(Serialize, Deserialize)]
struct RootInterface {
  "cat dog": i64,
}
```

**Comment by ritz078** [comment]
How do suggest to rename them ?

- for spaces I can change it to camel case
- for reserved keyword - prefix / postfix ?

Any suggestion for the second one ?

**Comment by Ameobea** [comment]
I'm a fan of just adding a underscore to the beginning.  `type` -> `_type`.

**Comment by ritz078** [comment]
fix deployed.
