### ISSUE TITLE
Feature request: Add support for HOCON

### ISSUE THREAD

**Issue by mslinn** [transform-it/transform-www#47]
[HOCON](https://github.com/typesafehub/config) is a JSON superset. Many parsers exist, including my favorites, [circe-config](https://github.com/circe/circe-config) and [PureConfig](https://github.com/pureconfig/pureconfig).

**Comment by ritz078** [comment]
I am not familiar with it but if anyone wants to submit a PR, I will gradly accept it.

**Comment by ritz078** [comment]
Don't think this one fits the website.
