### ISSUE TITLE
Project linting using ESLint and airbnb guide

### ISSUE THREAD

**Issue by gyandeeps** [transform-it/transform-www#51]
https://www.npmjs.com/package/eslint-config-airbnb

**Comment by ritz078** [comment]
prettier and these config don't go well together. Rather I would like to switch to prettier-standard which handles both linting and formatting.

**Comment by morajabi** [comment]
Prettier is superb. But we can use `prettier-eslint` and `eslint --fix` together too.

**Comment by ritz078** [comment]
@gyandeeps I think we should use `prettier-standard` and get rid of lot of config files. Also it will be great if it runs before every commit using husky and lint staged.

**Comment by morajabi** [comment]
I thought we have husky and lint staged... Yeah, they're perfect. I can add them tonight.

**Comment by morajabi** [comment]
@ritz078 Do you know prettier-standard follows [Standard Styleguid](https://github.com/standard/standard) which

**Comment by morajabi** [comment]
Shall we add Jest too for new features?

**Comment by ritz078** [comment]
What do you mean by new features ? All modules are in separate packages with their own tests. So I don't think its needed here.

**Comment by morajabi** [comment]
Oh, I see. I didn't notice that we no longer have transform modules here. Sorry, my bad.

**Comment by morajabi** [comment]
Done! #54
