### ISSUE TITLE
make svg optimization optional

### ISSUE THREAD

**Issue by ritz078** [transform-it/transform-www#58]

**Comment by morajabi** [comment]
Have you picked it up?

**Comment by ritz078** [comment]
No. I am a bit busy these days. You can pick it up if you want.

**Comment by morajabi** [comment]
OK! I just have a problem, when you return a promise from this function https://github.com/transform-it/transform-www/blob/master/pages/html-to-jsx.js#L24 where would you convert it to JSX then?

**Comment by ritz078** [comment]
I have just pushed the latest code. See if it makes sense now.

**Comment by morajabi** [comment]
I spend half an hour trying to figure this thing out. haha

**Comment by ritz078** [comment]
I am really sorry. I should keep that in mind or else I may be wasting someone's time. I will make sure this doesn't happen again. Again, Sorry.

**Comment by morajabi** [comment]
Oh, I didn't mean that way! You're awesome 100💯 One more thing it seems we don't have any space for another checkbox now?

**Comment by ritz078** [comment]
I am just taking it as a learning. Yes it seems so. I am open to ideas for the design fix. We can change the text from "react-native-svg" to "React Native". Maybe it gives some space ?

**Comment by morajabi** [comment]
Yea, it'll work for now but then we have to change the `ConversionPanel` prop api.

**Comment by ritz078** [comment]
Yes that's the only solution or I am fine to move the react native svg functionality to a completely separate route with a small note on the current page. I think that separation makes more sense here.

**Comment by ritz078** [comment]
are you working on this ?

**Comment by morajabi** [comment]
No, I want now... Should I separate then?

**Comment by ritz078** [comment]
Yes
