### ISSUE TITLE
Consider using https://www.npmjs.com/package/json-ts

### ISSUE THREAD

**Issue by shakyShane** [transform-it/transform-www#65]
If the the goal of converting JSON to typescript is to produce useful type/interfaces, then one should really choose [my implementation](https://www.npmjs.com/package/json-ts)

It supports more features that other libraries, has a simpler API, can merge multiple JSON blobs, and is more correct than any competition.

Please see the comparison table & tests for examples - if you have an interest in this, I'd be happy to send a PR

Thanks :)

**Comment by ritz078** [comment]
Hi @shakyShane ,

It looks great and really rich feature-wise. Currently, it seems that it can be used for JSON to Flow and JSON to Typescript. I am not sure how it can replace json-schema-to-typescript as it takes JSON as an input and not a JSON schema?

**Comment by shakyShane** [comment]
Ahh sorry, yes that's correct!

**Comment by ritz078** [comment]
I would love a PR :)

**Comment by ritz078** [comment]
it is live now. 🎉
