### ISSUE TITLE
Cursor jumps to end of the text when editing invalid json

### ISSUE THREAD

**Issue by Javier-Rotelli** [transform-it/transform-www#68]
First, thanks for this awesome tool! it's been saving me a lot of time lately :D 

so, i have some json that's not 100% valid
for example, i copied a js object, and i need to add quote marks around properties names
whenever i type something the cursor jumps to the end of the input
like this:
![Example](https://d2ffutrenqvap3.cloudfront.net/items/2o1t46093R2Q0o151M01/Screen%20Recording%202018-03-05%20at%2001.48%20PM.gif)

it's not that bad, i can always edit the source before pasting it. but it would be easier if i could just edit on the site, given that it already has a working JSON validator. 

Thanks!

**Comment by ritz078** [comment]
I am aware of this. I will try to fix it in few days. Should be an issue with codemirror. Thanks for reporting.

**Comment by ritz078** [comment]
should be fixed now.
