### ISSUE TITLE
[BAD PRACTICE] CSS to Emotion nested css`` rules

### ISSUE THREAD

**Issue by silicakes** [transform-it/transform-www#77]
In the following [example](https://transform.now.sh/css-to-emotion/), the transformer demonstrates the following rule:

```
.alert-dismissible .close {
    position: relative;
    top: -0.75rem;
    right: -1.25rem;
    padding: 0.75rem 1.25rem;
    color: inherit;
}
```

being converted into:

```
export const alertDismissible = css`
  & .${close} {
    position: relative;

    top: -0.75rem;

    right: -1.25rem;

    padding: 0.75rem 1.25rem;

    color: inherit;
  }
`
```

This should come with a warning as, per emotions [documentation](https://emotion.sh/docs/nested):

> To nest a class selector using the class generated with `css` you can interpolate it but this is strongly recommended against and should only be used in rare circumstances because it will break when used with [composition](https://emotion.sh/docs/composition).

Meaning that it'll break when trying to force specificity using `cx`

**Comment by ritz078** [comment]
Can you please post this issue on https://github.com/brikou/CSS-in-JS-generator?

**Comment by silicakes** [comment]
@ritz078 roger that.
