### ISSUE TITLE
available as a node/npm module

### ISSUE THREAD

**Issue by DanielFGray** [transform-it/transform-www#9]
It would be awesome if I could have a CLI version of this, takes stdin, some arguments, prints result.

Editor integration could become a thing.

**Comment by ritz078** [comment]
That is a great suggestion. I am going to separate the logic as a separate npm module soon. And that can be useful for creating a CLI.

**Comment by morajabi** [comment]
@ritz078 I think we need to make its own organization when we're going to separate it to packages.

**Comment by ritz078** [comment]
yes that's in my mind but I will wait till we have atleast two repos or I am very much up for having a monorepo. It will make development easier. Its a discussion we can have in a separate thread.

**Comment by morajabi** [comment]
@ritz078 You're right, it doesn't make sense to make one repo in its own org, but I meant at the time we were separating this to multiple packages.

**Comment by ritz078** [comment]
yes multiple packages but they all will combine to give one API. So I was thinking about a monorepo as testing will be easier and website will also be updated.

**Comment by morajabi** [comment]
For that, Yes, but what about CLI or maybe in future editor extensions?

**Comment by ritz078** [comment]
Same package will also have a CLI and API usage. There's still time for editor extensions. So once we reach that stage I will definitely move this to an org. I just think that the core tool will be part of single repo and when there something extra based on that tool (like extensions), I will create an org. Does this sound good to you. I am also willing to move to an org but after we have the tool ready ? What are your views ?

**Comment by ritz078** [comment]
I have created separate NPM packages : 

- **JSON to flow, TS, scala, rust serde** : [transform-json-types](https://github.com/transform-it/transform-json-types)
- **CSS-to-JS** : [transform-css-to-js](https://github.com/transform-it/transform-css-to-js)
- **JSON to PropTypes** : [babel-plugin-json-to-proptypes](https://github.com/transform-it/babel-plugin-json-to-proptypes)
- **GraphQL to TS, Flow** : [transform-graphql-type-annotations](https://github.com/transform-it/transform-graphql-type-annotations)

From community : 
- **JSON to Mongo, BigQuery, MySQL** - [generate-schema](https://github.com/nijikokun/generate-schema)

I hope this will help people build editor extensions. If anyone is interested I can add him to the organisation.

**Comment by morajabi** [comment]
Great!

**Comment by DanielFGray** [comment]
I threw this together in 20 minutes or so: https://github.com/danielfgray/transform-cli/blob/master/index.js

`curl somejson | node ./index.js -t flow` will print flow types for the given json

Needs a lot of polish, I'll happily transfer it wherever

**Comment by ritz078** [comment]
@DanielFGray Looks great. I have sent you an invite to the organisation. You can add it in the org.
