### ISSUE TITLE
Typescript to JSON Schema

### ISSUE THREAD

**Issue by davo** [transform-it/transform-www#99]
Input:
```ts
interface Client {
	firstName: string
	lastName: string
	nickName: string
	age: number
}
```

Expected output:

```json
  "id": "Client",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "nickName": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "required": [
    "firstName",
    "lastName",
    "nickName",
    "age"
  ],
  "additionalProperties": false
}
```

> `Output generated with typson`.

Not really sure how to make this happen or help out, but I'm willing to learn how to do it 🤓

Related projects:

- [typescript-json-schema](https://github.com/YousefED/typescript-json-schema)
- [typson](https://github.com/lbovet/typson)

**Comment by ritz078** [comment]
None of them will ensure the right output. Any JSON schema you get from TypeScript won't be trustworthy. for example, a `number` in TS can be any of `number` or `integer` in JSON Schema.
